import './profiles-layout.html'
import '../pages/profile.js'
import '../partials/navigation.js'
import '../pages/not-found.js'
import '../pages/profiles-directory.js'
import '../pages/teams-directory.js'
